import { Metadata } from "next";
import Header from "./components/Header";
import HomePage from "./components/Home";
import Categories from "./components/Categories";
import SuperHotRecipes from "./components/SuperHotRecipes";
import Chief from "./components/Chief";

export const metadata: Metadata = {
  title: "Foodieland | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Header/>
      <HomePage/>
      <Categories/>
      <SuperHotRecipes/>
      <Chief/>
    </>
  );
}